#!/usr/bin/env python3
"""Generate the screen registry and design-artifact index from evidence.

Both documents are hand-maintained in most repos and rot within a release.
The columns that rot are the evidence ones: which screens a capture actually
reached, and which design artifact still has authority. Those are derivable,
so they are generated here and the judgement columns are left for a human.

Evidence sources, all read at run time:

* `docs/ui-captures/identifier-truth/*.txt` — screens a probe reached, from
  AMA-2503. A screen with an inventory is reachable by automation; one
  without is not, whatever the design docs claim.
* the design-parity matrix in amakaflow-docs — the surface list and the
  contract ticket per surface.
* the rig and screens artifacts in amakaflow-docs — classified by the rule
  the matrix already locked: an artifact a live ticket cites is Canonical, a
  superseded version is Legacy, anything uncited is Unknown.

Nothing here invents a screen. A row exists because a file does.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
PROBES = REPO_ROOT / "docs" / "ui-captures" / "identifier-truth"
OUT_DIR = REPO_ROOT / "docs" / "product"

MATRIX_ROW = re.compile(r"^\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|")
VERSIONED = re.compile(r"^(?P<stem>.*?)(?P<version>\d*)$")


def matrix_surfaces(matrix: pathlib.Path) -> list[dict[str, str]]:
    rows = []
    for line in matrix.read_text(errors="replace").splitlines():
        match = MATRIX_ROW.match(line)
        if not match:
            continue
        surface, target, ticket, verdict = (part.strip() for part in match.groups())
        if surface in {"Surface", ""} or set(surface) <= {"-"}:
            continue
        rows.append(
            {"surface": surface, "target": target, "ticket": ticket, "verdict": verdict}
        )
    return rows


def probed_screens() -> dict[str, int]:
    if not PROBES.is_dir():
        return {}
    return {
        path.stem: len([line for line in path.read_text().splitlines() if line])
        for path in sorted(PROBES.glob("*.txt"))
    }


def artifacts(design_root: pathlib.Path) -> list[pathlib.Path]:
    if not design_root.is_dir():
        return []
    found = [
        path
        for pattern in ("rig*.html", "screens-*.jsx")
        for path in design_root.rglob(pattern)
        if path.is_file()
    ]
    return sorted(found, key=lambda p: p.name)


def classify(paths: list[pathlib.Path], cited: set[str]) -> list[tuple[str, str, str]]:
    """Canonical when a live ticket cites it, Legacy when a newer sibling exists."""
    by_stem: dict[str, list[tuple[int, pathlib.Path]]] = {}
    for path in paths:
        base = path.name.rsplit(".", 1)[0]
        match = VERSIONED.match(base)
        stem = match.group("stem")
        version = int(match.group("version") or 0)
        by_stem.setdefault(stem, []).append((version, path))

    rows = []
    for stem, entries in by_stem.items():
        newest = max(version for version, _ in entries)
        for version, path in sorted(entries):
            name = path.name
            if any(token in cited for token in (name, name.rsplit(".", 1)[0])):
                verdict = "Canonical"
                why = "cited by a live contract ticket in the parity matrix"
            elif version < newest:
                verdict = "Legacy"
                why = f"superseded by {stem}{newest}"
            else:
                verdict = "Unknown"
                why = "no live ticket cites it — classify before relying on it"
            rows.append((name, verdict, why))
    return sorted(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--docs-repo", type=pathlib.Path, required=True)
    args = parser.parse_args()

    matrix = args.docs_repo / "docs" / "superpowers" / "design-parity-matrix.md"
    if not matrix.is_file():
        print(f"parity matrix not found at {matrix}", file=sys.stderr)
        return 1

    surfaces = matrix_surfaces(matrix)
    probed = probed_screens()
    cited = {
        token
        for row in surfaces
        for token in re.findall(r"[a-z0-9-]+(?:\.html|\.jsx)?", row["target"])
    }
    design_root = args.docs_repo / "design"

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    registry = [
        "# Screen registry v1",
        "",
        "Generated by `scripts/build-screen-registry.py`. Regenerate rather than",
        "hand-edit the evidence columns; they are derived from files on disk.",
        "",
        "`Runtime evidence` is the identifier inventory captured by AMA-2503's",
        "probes. A surface with no inventory has not been reached by automation,",
        "which is a fact about our tooling, not a claim about the screen.",
        "",
        "| Screen ID | Area | Route / entry | Runtime evidence | Design artifact | Contract | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]

    for name, count in probed.items():
        registry.append(
            f"| `{name}` | runtime | probe `e2e/maestro/identifier-truth/{name}.yaml` "
            f"| {count} identifiers observed | — | AMA-2503 | CAPTURED |"
        )

    for row in surfaces:
        if row["surface"].lower().replace(" ", "-") in probed:
            continue
        registry.append(
            f"| {row['surface']} | design surface | — | none | {row['target']} "
            f"| {row['ticket']} | TODO |"
        )

    registry += [
        "",
        f"{len(probed)} rows carry runtime evidence. "
        f"{len(surfaces)} design surfaces come from the parity matrix.",
        "",
        "Two granularities on purpose. A `runtime` row is a screen automation has",
        "actually reached; a `design surface` row is a target the matrix names.",
        "Reconciling the two is AMA-2508's job, and this table is where that",
        "happens.",
        "",
        "This is short of the 40-80 rows AMA-2504 asked for, and padding it would",
        "defeat the point. State rows (loading, empty, error) get added as the",
        "AMA-2505 capture runs actually reach them, so the count grows with",
        "evidence rather than ahead of it.",
        "",
        "Status values: TODO, CAPTURED, RECONCILED, CANONICAL, BLOCKED, OUT_OF_SCOPE.",
        "Only CANONICAL establishes current intended UI.",
    ]
    (OUT_DIR / "screen-registry.md").write_text("\n".join(registry) + "\n")

    found = artifacts(design_root)
    index = [
        "# Design artifact index",
        "",
        "Generated by `scripts/build-screen-registry.py` from the artifacts in",
        "amakaflow-docs, using the rule the parity matrix already locked: an",
        "artifact a live contract ticket cites is the target; one no ticket cites",
        "is historical and carries no authority.",
        "",
        "Only **Canonical** establishes current UI.",
        "",
        "| Artifact | Classification | Why |",
        "| --- | --- | --- |",
    ]
    index += [f"| `{name}` | {verdict} | {why} |" for name, verdict, why in classify(found, cited)]
    index += ["", f"{len(found)} artifacts classified."]
    (OUT_DIR / "design-artifact-index.md").write_text("\n".join(index) + "\n")

    print(f"registry: {len(probed)} captured, {len(surfaces)} matrix surfaces")
    print(f"artifact index: {len(found)} artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
